name: CI/CD Pipeline

on:
  push:
    branches:
      - master	# Trigger pipeline on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

          
    # Debug Host
      - name: Debug Host
        run: |
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          ping -c 4 ${{ secrets.EC2_HOST }}

     # Deploy to EC2
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem 
          echo "Deploying to EC2 at ${{ secrets.EC2_HOST }}"
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
          cd /var/www/flask_app
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flask_app
          EOF
          rm ec2_key.pem
